"use client";

import type { ShoppingList as ShoppingListType, StoreSection } from "@/types/shopping";
import { getSectionDisplayName, getSectionOrder } from "@/lib/services/shopping/section-classifier";
import { formatQuantity } from "@/lib/services/shopping/unit-reconciliation";

interface PrintViewProps {
  list: ShoppingListType;
  mealName?: string;
}

/**
 * Print-optimized shopping list view
 *
 * Renders without interactive elements, with checkbox squares
 * for manual check-off and a compact layout.
 */
export function PrintView({ list, mealName }: PrintViewProps) {
  // Group items by section
  const itemsBySection = new Map<StoreSection, typeof list.items>();

  for (const item of list.items) {
    // Don't show staples in print view (they're items you already have)
    if (item.isStaple) continue;

    const section = item.section;
    if (!itemsBySection.has(section)) {
      itemsBySection.set(section, []);
    }
    itemsBySection.get(section)?.push(item);
  }

  // Sort sections by store order
  const sortedSections = Array.from(itemsBySection.entries()).sort(
    ([a], [b]) => getSectionOrder(a) - getSectionOrder(b)
  );

  const today = new Date().toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const totalItems = list.items.filter((i) => !i.isStaple).length;

  return (
    <div className="print-view p-8 max-w-[8.5in] mx-auto font-sans text-black bg-white">
      {/* Header */}
      <header className="mb-6 pb-4 border-b-2 border-black">
        <h1 className="text-2xl font-bold mb-1">Shopping List</h1>
        {mealName && <p className="text-lg">{mealName}</p>}
        <p className="text-sm text-gray-600">{today}</p>
        <p className="text-sm text-gray-500 mt-1">{totalItems} items</p>
      </header>

      {/* Sections */}
      <div className="space-y-6">
        {sortedSections.map(([section, items]) => (
          <section key={section}>
            <h2 className="font-bold text-lg mb-2 pb-1 border-b border-gray-300">
              {getSectionDisplayName(section)}
            </h2>
            <ul className="space-y-1.5">
              {items.map((item) => {
                const quantityDisplay =
                  item.quantity !== null
                    ? `${formatQuantity(item.quantity)}${item.unit ? ` ${item.unit}` : ""}`
                    : "";

                return (
                  <li key={item.id} className="flex items-start gap-3">
                    {/* Checkbox square */}
                    <span className="inline-block w-4 h-4 border border-gray-400 flex-shrink-0 mt-0.5" />

                    {/* Content */}
                    <span className="flex-1">
                      {quantityDisplay && (
                        <span className="font-medium mr-2">
                          {quantityDisplay}
                        </span>
                      )}
                      <span>{item.name}</span>
                      {item.notes && (
                        <span className="text-gray-500 text-sm ml-2">
                          ({item.notes})
                        </span>
                      )}
                    </span>
                  </li>
                );
              })}
            </ul>
          </section>
        ))}
      </div>

      {/* Footer */}
      <footer className="mt-8 pt-4 border-t border-gray-300 text-sm text-gray-500 text-center">
        Generated by Sunday Dinner
      </footer>

      {/* Print styles */}
      <style jsx>{`
        @media print {
          .print-view {
            padding: 0.5in;
            font-size: 11pt;
          }

          h1 {
            font-size: 18pt;
          }

          h2 {
            font-size: 14pt;
          }

          ul {
            break-inside: avoid;
          }

          li {
            break-inside: avoid;
          }

          section {
            break-inside: avoid-page;
          }
        }

        @page {
          margin: 0.5in;
          size: letter;
        }
      `}</style>
    </div>
  );
}
