-- Migration: Create timelines and tasks tables
-- Sunday Dinner v1 - Cooking timeline with conflict detection

-- Create enum for task status
create type task_status as enum (
  'pending',      -- Not yet started
  'in_progress',  -- Currently being worked on
  'completed',    -- Done
  'skipped'       -- User chose to skip
);

-- Create timelines table
create table if not exists timelines (
  id uuid primary key default gen_random_uuid(),
  meal_id uuid not null references meals(id) on delete cascade,

  -- Conflict tracking (computed from tasks, stored for quick access)
  has_conflicts boolean not null default false,
  conflicts jsonb not null default '[]'::jsonb,
  -- Each conflict: { type, taskIds, description, severity }

  -- Live execution state
  is_running boolean not null default false,
  started_at timestamptz,  -- When "Start Cooking" was pressed
  current_task_id uuid,    -- The "Now" task (populated during execution)

  -- Timestamps
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  -- One timeline per meal
  unique(meal_id)
);

-- Apply updated_at trigger to timelines
create trigger timelines_updated_at
  before update on timelines
  for each row
  execute function update_updated_at_column();

-- Create tasks table
create table if not exists tasks (
  id uuid primary key default gen_random_uuid(),
  timeline_id uuid not null references timelines(id) on delete cascade,
  meal_id uuid not null references meals(id) on delete cascade,
  recipe_id uuid not null references recipes(id) on delete restrict,

  -- Optional link to specific instruction step
  instruction_id uuid,  -- ID within recipe's instructions JSONB

  -- Task content
  title text not null,
  description text,

  -- Timing (relative to serve time)
  -- Negative = before serve, e.g., -120 = 2 hours before
  start_time_minutes integer not null,
  duration_minutes integer not null check (duration_minutes > 0),
  end_time_minutes integer not null,  -- Computed: start + duration

  -- Oven constraints (for conflict detection)
  requires_oven boolean not null default false,
  oven_temp integer check (oven_temp > 0 or oven_temp is null),

  -- Dependencies (task IDs that must complete first)
  depends_on uuid[] default '{}',

  -- Execution status
  status task_status not null default 'pending',
  completed_at timestamptz,
  notes text,

  -- Validation state (set by deterministic validator)
  is_valid boolean default true,
  validation_errors text[] default '{}',

  -- Order for display
  sort_order integer not null default 0,

  -- Timestamps
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Apply updated_at trigger to tasks
create trigger tasks_updated_at
  before update on tasks
  for each row
  execute function update_updated_at_column();

-- Create indexes for common queries
create index idx_timelines_meal_id on timelines(meal_id);
create index idx_timelines_is_running on timelines(is_running) where is_running = true;

create index idx_tasks_timeline_id on tasks(timeline_id);
create index idx_tasks_meal_id on tasks(meal_id);
create index idx_tasks_recipe_id on tasks(recipe_id);
create index idx_tasks_status on tasks(status);
create index idx_tasks_start_time on tasks(start_time_minutes);
create index idx_tasks_sort_order on tasks(timeline_id, sort_order);

-- Partial index for oven tasks (conflict detection)
create index idx_tasks_oven on tasks(timeline_id, start_time_minutes, end_time_minutes)
  where requires_oven = true;

-- Add comments for documentation
comment on table timelines is 'Cooking timeline for a meal - generated by Claude, validated deterministically';
comment on column timelines.conflicts is 'JSONB array of detected conflicts: [{type, taskIds, description, severity}]';
comment on table tasks is 'Individual cooking tasks with timing relative to serve time';
comment on column tasks.start_time_minutes is 'Minutes relative to serve time (negative = before)';
comment on column tasks.depends_on is 'Array of task UUIDs that must complete before this task';

-- Add foreign key for current_task_id after tasks table exists
alter table timelines
  add constraint fk_timelines_current_task
  foreign key (current_task_id) references tasks(id) on delete set null;
